# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephanie Bagwell, Psy.D.
email: skbagwell@gmail.com
description: > # Making changes in life is not always easy, but also not impossible.
  Gain the insight you need to make lasting changes in your life. In an encouraging, safe,
  and supportive environment you can explore your thoughts and feelings. Learn to develop the
  confidence and skills to be a happy, healthy, and successful individual.
  I provide individual, couples, child, and family therapy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://billhinderman.github.io/steph-jekyll/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
